apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-cluster
spec:
  instances: 2

  imageName: ghcr.io/cloudnative-pg/postgresql:15

  storage:
    size: 1Gi

  bootstrap:
    initdb:
      database: projectdb
      owner: appuser
      secret:
        name: app-secret